
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/bank_db}
      port: 27017


  application:
    name: order-service

server:
  port: 8083
